FROM rust:alpine3.17 AS builder

RUN apk add --no-cache musl-dev
WORKDIR /app
COPY . .
RUN cargo build --release 

FROM alpine:3.17
COPY --from=builder /app/target/release/zola /usr/local/bin/zola
RUN apk add --no-cache git
ENTRYPOINT [ "zola" ]
